# Generated by Django 4.1.7 on 2023-03-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_remove_person_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
