# Generated by Django 4.1.7 on 2023-03-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_person_address_alter_person_date_of_join_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hair_color',
            field=models.CharField(default='Brown', max_length=255),
            preserve_default=False,
        ),
    ]
