# Generated by Django 4.1.7 on 2023-03-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0006_person_hair_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='hair_color',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='courses.course'),
        ),
    ]
